purbeurre/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as users_views


urlpatterns = [
    path("admin/", admin.site.urls),
    # if path is empty, will look for views in the search app
    path("", include("search.urls")),
    path("register/", users_views.register, name="register"),
    path("account/", users_views.account, name="account"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"),
        name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout",
    ),
]

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("products/", views.products, name="products"),
    path("product/<int:product_id>/", views.product, name="product"),
    path("substitutes/<int:product_id>/",
         views.substitutes, name="substitutes"),
    path("save_favorite/<int:product_id>/<int:substitute_id>/",
         views.save_favorite, name="save_favorite"),
    path("favorites/",
         views.favorites, name="favorites"),
     path("legal_notice/", views.legal_notice, name="legal_notice"),
]

search/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    """Represents the category table"""

    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Represents the product table"""

    name = models.CharField(max_length=150, unique=True)
    brands = models.CharField(max_length=150)
    barcode = models.CharField(max_length=13, unique=True)
    nutriscore = models.CharField(max_length=1)
    url = models.URLField()
    image_url = models.URLField()
    image_small_url = models.URLField()
    energy_100g = models.FloatField(default=0, null=True)  # can be empty
    sugars_100g = models.FloatField(default=0, null=True)
    sodium_100g = models.FloatField(default=0, null=True)
    fat_100g = models.FloatField(default=0, null=True)
    salt_100g = models.FloatField(default=0, null=True)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return f"{self.name}, {self.nutriscore}"


class Favorite(models.Model):
    """Represents the favorite table
    product: linked to product by ForeignKey
    substitute: linked to product by ForeignKey
    user: linked to user by ForeignKey
    1 user can have different favorites
    """

    # CASCADE:if is deleted in Products'table,
    # will be deleted here NOT the opposite
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="favorite_product"
    )
    substitute = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="favorite_substitute"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="favorite_user"
    )

    def __str__(self):
        return (
            f"Produit: {self.product}, Substitut: {self.substitute}, User: {self.user}"
        )

search/forms.py
"""Creates forms for 'search' app"""

from django import forms


class MainSearchForm(forms.Form):
    """Represents the main search form on the home page"""
    product_search = forms.CharField(
        label="",
        max_length=70,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Entrez un produit",
                "class": "form-control",
                "type": "text",
                "autofocus": "autofocus",
            }
        ),
    )


class NavSearchForm(forms.Form):
    """Represents the search form on the navigation bar"""
    product_search = forms.CharField(
        label="",
        max_length=70,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Entrez un produit",
                "class": "form-control",
                "type": "text",
            }
        ),
    )

search/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from .forms import MainSearchForm
from .models import Product, Category, Favorite
from users.models import User


def home(request):
    """Displays the home page"""
    main_search_form = MainSearchForm()  # instanciate form
    context = {
        "main_search_form": main_search_form,
        # key: variables we access from template
    }
    return render(request, "search/home.html", context)


def products(request):
    """Displays the result page with list of products according to user input"""
    if request.method == "POST":
        # get the value of name="" from template
        product_search = request.POST["product_search"]
        # products = query made to DB
        # query: max 6 pdcts where name contains value of product_search
        # normalized as in feed_db.py
        products = Product.objects.all().filter(
            name__contains=product_search.strip().lower().capitalize()
        )[:6]
        context = {
            # title in HTML will contain value of product_search
            "title": product_search,
            "products": products,
        }
        # send context to products.html template and render this template
        return render(request, "search/products.html", context)


def product(request, product_id):
    """Displays the product details page

    Args:
        product_id (int): Id of the product
    """
    # try:
    product = Product.objects.get(pk=product_id)
    context = {"product": product}
    # except Product.DoesNotExist:
    return render(request, "search/product.html", context)


def substitutes(request, product_id):
    """Displays the result page with list of substitutes for the selected product
    
    Args:
        product_id (int): Id of the product"""
    # Find product searched by user with id
    product_query = Product.objects.get(pk=product_id)

    # Find categories of the searched_product
    product_query_cat = Category.objects.filter(product__id=product_query.id)

    # Find max 9 substitutes with better nutriscore
    # and at least 3 categories in common
    substitutes = (
        Product.objects.filter(categories__in=product_query_cat)
        .annotate(nb_cat=Count("categories"))
        .filter(nb_cat__gte=3)
        .filter(nutriscore__lt=product_query.nutriscore)
        .order_by("nutriscore")[:9]
    )

    context = {"product": product_query, "substitutes": substitutes}

    return render(request, "search/substitutes.html", context)


@login_required
def save_favorite(request, product_id, substitute_id):
    """Saves the substitute and product searched as favorite
    if user is logged in"""

    product = Product.objects.get(pk=product_id)
    substitute = Product.objects.get(pk=substitute_id)
    user = User.objects.get(
        pk=request.user.id
    )  # request.user for current user connected
    favorite = Favorite(product=product, substitute=substitute, user=user)

    # Save this as a favorite in DB
    try:
        favorite.save()
        return redirect("search:favorites")
    except IntegrityError:
        return redirect("search:home")


@login_required
def favorites(request):
    """Displays the favorites for the logged in user"""

    # Find favorites in DB according to user id
    favorites = Favorite.objects.filter(user_id=request.user.id)

    context = {
        "favorites": favorites,
    }

    return render(request, "search/favorites.html", context)


def legal_notice(request):
    """Displays the legal notice page with infos"""
    return render(request, "search/legal_notice.html")

search/templates/search/favorites.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- Favorites -->
<header class="products">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center"
    >
      <div class="col-lg-10 align-self-end">
        <h2 class="text-white font-weight-bold">Mes aliments</h2>
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light" id="products">
  <div class="container">
    <div class="row">
      {% if favorites %}
      <div class="col-12">
        <h3 class="text-center">
          Voici les substituts que vous avez enregistré :
        </h3>
      </div>
      {% for favorite in favorites %}
      <div class="col-lg-4 col-md-12">
        <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
          <img
            class="card-img-top"
            src="{{ favorite.substitute.image_url }}"
            alt="image du substitut"
          />

          <span class="card-score-{{ favorite.substitute.nutriscore }}"
            >{{ favorite.substitute.nutriscore }}</span
          >

          <div class="card-body text-center">
            <a
              href="{% url 'search:product' favorite.substitute.id %}"
              target="_blank"
            >
              <p class="card-title">{{ favorite.substitute.name }}</p>
            </a>
            <p>est un substitut pour</p>
            <a
              href="{% url 'search:product' favorite.product.id %}"
              target="_blank"
            >
              <p class="card-title">{{ favorite.product.name }}</p>
            </a>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="text-center col-12">
        Vous n'avez pas encore enregistré des substituts en favoris. Une
        recherche en tête ?
        <div class="p-3">
          <a href="{% url 'search:home' %}" class="btn btn-primary"
            >C'est par ici.</a
          >
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</section>

{% endblock content %}

search/templates/search/home.html
{% extends 'base.html' %} {% block content %} {% load static %} {% load crispy_forms_tags %}
<!-- Masthead-->
<header class="masthead">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center"
    >
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">
          Du gras, oui, mais de qualité !
        </h1>
        <h2 class="text-white-50">
          Trouvez un produit de substitution pour ceux que vous consommez tous
          les jours.
        </h2>
        <hr class="divider my-4" />
      </div>
      <div class="col-lg-8 align-self-baseline">
        <form id="main_form" action="{% url 'search:products' %}" method="POST">
          {% csrf_token %} {{ main_search_form }}
          <input
            class="input-group-append btn btn-primary"
            type="submit"
            value="Rechercher"
          />
        </form>
      </div>
    </div>
  </div>
</header>
<!-- About-->
<section class="page-section bg-secondary" id="about">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="text-white mt-0">Colette et Remy</h2>
        <hr class="divider primary my-4" />
        <p class="text-white-50 mb-4">
          Pur Beurre est l'initiative de deux amoureux de la gastronomie
          française, Colette Tatou et Rémy, que vous avez déjà certainement
          rencontrés dans notre excellent restaurant Ratatouille.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <p class="text-white">Colette</p>
        <img
          class="img-owners"
          src="{% static '/assets/img/colette-4.jpg' %}"
        />
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <p class="text-white">Remy</p>
        <img class="img-owners" src="{% static 'assets/img/remy-8.jpg' %}" />
      </div>
    </div>
  </div>
</section>

<!-- Contact-->
<section class="page-section" id="contact">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Contactez-nous!</h2>
        <hr class="divider my-4" />
        <p class="text-muted mb-5">
          Une question? Une suggestion? N'hésitez pas à nous contacter par email
          ou téléphone.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
        <div>+33 1 01010101</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
        <a class="d-block" href="mailto:contact@yourwebsite.com"
          >contact@yourwebsite.com</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock %}

search/templates/search/legal_notice.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- Legal notice -->
<header class="products">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center"
    >
      <div class="col-lg-10 align-self-end">
        <h1 class="text-white font-weight-bold">Mentions légales</h1>
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-12 mx-auto">
        <p>
          Site réalisé par <a href="https://github.com/Lamia7">Lamia</a> dans le
          cadre du projet scolaire du parcours Développeur d'application Python
          d'
          <a href="https://openclassrooms.com/fr/paths" target="_blank"
            >Openclassrooms</a
          >.
        </p>

        <ul>
          <li>
            <span class="font-weight-bold">Thème :</span>
            <a
              href="https://startbootstrap.com/themes/creative/"
              target="_blank"
              >Template Bootstrap Creative</a
            >
          </li>
          <li>
            <span class="font-weight-bold">Données des produits:</span> API
            <a href="https://world.openfoodfacts.org/data" target="_blank"
              >OpenFoodFacts</a
            >
          </li>

          <li>
            <span class="font-weight-bold"
              >Ressources graphiques pour les icônes:</span
            >
            <a href="https://fontawesome.com/" target="_blank">Font Awesome</a>
          </li>

          <li>
            <span class="font-weight-bold">Hébergeur :</span>
            <a href="https://www.heroku.com/">Heroku</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

search/templates/search/product.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- Products -->
  <header
    class="products"
    style="
  background: linear-gradient(
      to bottom,
      rgba(92, 77, 66, 0.8) 0%,
      rgba(92, 77, 66, 0.8) 100%
    ), url(
      {% if product.image_url %}{{ product.image_url}}
      {% else %}{% static '/assets/img/ratatouille-11.jpg' %}
      {% endif %}); 
    background-repeat: no-repeat; background-position: center; background-size: contain;"
  >
    <div class="container h-100">
      <div
        class="row h-100 align-items-center justify-content-center text-center"
      >
        <div class="col-lg-10 align-self-end">
          <h2 class="text-white font-weight-bold">{{ product.name }}</h2>
        </div>
      </div>
    </div>
  </header>
  <section class="page-section bg-light" id="products">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-12">
          <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
            {% if product.nutriscore == "A" %}
            <img
              class="card-img-top"
              src="{% static '/assets/img/nutriscore-A.png' %}"
              alt="logo nutriscore A"
            />
            {% elif product.nutriscore == "B" %}
            <img
              class="card-img-top"
              src="{% static '/assets/img/nutriscore-B.png' %}"
              alt="logo nutriscore B"
            />
            {% elif product.nutriscore == "C" %}
            <img
              class="card-img-top"
              src="{% static '/assets/img/nutriscore-C.png' %}"
              alt="logo nutriscore C"
            />
            {% elif product.nutriscore == "D" %}
            <img
              class="card-img-top"
              src="{% static '/assets/img/nutriscore-D.png' %}"
              alt="logo nutriscore D"
            />
            {% elif product.nutriscore == "E" %}
            <img
              class="card-img-top"
              src="{% static '/assets/img/nutriscore-E.png' %}"
              alt="logo nutriscore E"
            />
            {% endif %}
          </div>
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
            <div class="card-body text-center">
              <h4>Repères nutritionnels pour 100g</h4>
              <ul class="list-unstyled">
                <li>Energie : {{ product.energy_100g }}</li>
                <li>Sucres : {{ product.sugars_100g }}</li>
                <li>Sodium : {{ product.sodium_100g }}</li>
                <li>Graisses : {{ product.fat_100g }}</li>
                <li>Sel : {{ product.salt_100g }}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-12 col-md-12 text-center">
          <a href="{{ product.url }}" class="btn btn-primary" target="_blank"
            >Voir la fiche d'Openfoodfacts</a
          >
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}
</header>

search/templates/search/products.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- Products -->
<header class="products">
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center"
    >
      <div class="col-lg-10 align-self-end">
        <h1 class="text-white font-weight-bold">{{ title }}</h1>
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light" id="products">
  <div class="container">
    <div class="row">
      {% if products %}
      <div class="col-12">
        <h3 class="text-center">Voici le résultat de votre recherche :</h3>
      </div>
      {% for product in products %}
      <div class="col-lg-4 col-md-12">
        <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
          <img
            class="card-img-top"
            src="{{ product.image_url }}"
            alt="image du produit"
          />
          <span class="card-score-{{ product.nutriscore }}"
            >{{ product.nutriscore }}</span
          >

          <div class="card-body text-center">
            <a href="{% url 'search:product' product.id %}" target="_blank">
              <p class="card-title">{{ product.name }}</p>
            </a>
            <a
              href="{% url 'search:substitutes' product.id %}"
              class="btn btn-primary"
              >Substituer</a
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="text-center col-12">
        Désolé, nous n'avons pas trouvé de produit correspondant à votre
        recherche. Une autre recherche en tête ?
        <div class="p-3">
          <a href="{% url 'search:home' %}" class="btn btn-primary"
            >C'est par ici.</a
          >
        </div>
      </div>

      {% endif %}
    </div>
  </div>
</section>
{% endblock content %}

search/templates/search/substitutes.html
{% extends 'base.html' %} {% block content %} {% load static %}

<!-- Substitutes -->
<header
  class="products"
  style="
  background: linear-gradient(
      to bottom,
      rgba(92, 77, 66, 0.8) 0%,
      rgba(92, 77, 66, 0.8) 100%
    ), url(
      {% if product.image_url %}{{ product.image_url}}
      {% else %}{% static '/assets/img/ratatouille-11.jpg' %}
      {% endif %}); 
    background-repeat: no-repeat; background-position: center; background-size: contain;"
>
  <div class="container h-100">
    <div
      class="row h-100 align-items-center justify-content-center text-center"
    >
      <div class="col-lg-10 align-self-end">
        <h2 class="text-white font-weight-bold">{{ product.name }}</h2>
      </div>
    </div>
  </div>
</header>
<section class="page-section bg-light" id="products">
  <div class="container">
    <div class="row">
      {% if substitutes %}
      <div class="col-12">
        <h3 class="text-center">
          Voici les substituts possibles pour ce produit :
        </h3>
      </div>
      {% for substitute in substitutes %}
      <div class="col-lg-4 col-md-12">
        <div class="card mx-1 my-3 shadow p-3 mb-5 bg-white rounded">
          <img
            class="card-img-top"
            src="{{ substitute.image_url }}"
            alt="image du produit"
          />
          <span class="card-score-{{ substitute.nutriscore }}"
            >{{ substitute.nutriscore }}</span
          >

          <div class="card-body text-center">
            <a href="{% url 'search:product' substitute.id %}" target="_blank">
              <p class="card-title">{{ substitute.name }}</p>
            </a>
            {% if user.is_authenticated %}
            <a
              href="{% url 'search:save_favorite' product.id substitute.id %}"
              class="btn btn-primary"
              >Sauvegarder</a
            >

            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %} {% else %}

      <div class="text-center col-12">
        Désolé, nous n'avons pas trouvé de substitut à ce produit. Une autre
        recherche en tête ?
        <div class="p-3">
          <a href="{% url 'search:home' %}" class="btn btn-primary"
            >C'est par ici.</a
          >
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  {% if user.is_authenticated == False %}
  <p class="pt-5 text-center">
    Vous pouvez enregistrer des substituts sur votre espace "Mes aliments".
  </p>
  <div class="text-center">
    <a href="{% url 'login' %}" class="btn btn-primary">Me connecter</a>
    <a href="{% url 'register' %}" class="btn btn-secondary">M'inscrire</a>
  </div>
  {% endif %}
</section>

{% endblock content %}