purbeurre/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from users import views as users_views


urlpatterns = [
    path("admin/", admin.site.urls),
    # if path is empty, will look for views in the search app
    path("", include("search.urls")),
    path("register/", users_views.register, name="register"),
    path("account/", users_views.account, name="account"),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"),
        name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout",
    ),
]

search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path("", views.home, name="home"),
    path("home/", views.home, name="home"),
    path("products/", views.products, name="products"),
    path("product/<int:product_id>/", views.product, name="product"),
    path("substitutes/<int:product_id>/",
         views.substitutes, name="substitutes"),
    path("save_favorite/<int:product_id>/<int:substitute_id>/",
         views.save_favorite, name="save_favorite"),
    path("favorites/",
         views.favorites, name="favorites"),
     path("legal_notice/", views.legal_notice, name="legal_notice"),
]

templates/base.html
<!DOCTYPE html>
<html lang="fr">
  {% load static %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pur Beurre</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/img/logo_pur_beurre-favicon.png' %}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v5.15.1/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Third party plugin CSS-->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body id="page-top">
    <!-- Navigation-->
    <nav
      class="navbar navbar-expand-lg navbar-light fixed-top py-3"
      id="mainNav"
    >
      <div class="container">
        <a
          class="navbar-brand js-scroll-trigger"
          href="{% url 'search:home' %}"
        >
          <img
            class="img-navbar"
            src="{% static 'assets/img/logo_pur_beurre.png' %}"
            alt="logo"
          />
          <span class="ml-2">Pur Beurre</span></a
        >
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto my-2 my-lg-0">
            <li class="nav-item">
              <div class="input-group input-group-sm">
                <form action="{% url 'search:products' %}" method="POST">
                  {% csrf_token %} {{ nav_search_form }}
                </form>
              </div>
            </li>
            <li class="nav-item">
              {% if user.is_authenticated %}
              <a
                id="mon_compte"
                class="nav-link js-scroll-trigger"
                href="{% url 'account' %}"
                title="Mon compte"
              >
                <i class="fa-2x fas fa-user-alt"></i>
              </a>
              {% else %}
              <a
                class="nav-link js-scroll-trigger"
                href="{% url 'login' %}"
                title="Se connecter"
              >
                <i class="fa-2x fas fa-sign-in-alt"></i>
              </a>
              {% endif %}
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="{% url 'search:favorites' %}"
                title="Mes aliments"
              >
                <i class="fa-2x fas fa-carrot"></i>
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link js-scroll-trigger"
                href="{% url 'logout' %}"
                title="Se déconnecter"
                ><i class="fa-2x fas fa-sign-out-alt"></i
              ></a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock content %}

    <!-- Footer-->
    <footer class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
            <a href="{% url 'search:legal_notice' %}">Mentions légales</a>
          </div>
          <div class="col-lg-4 mr-auto text-center mb-5 mb-lg-0">
            <a href="{% url 'search:home' %}#contact">Contact</a>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>